language: clojure
lein: 2.7.1

after_success:
  - lein uberjar

deploy:
  provider: releases
  api_key: "$RELEASE_OAUTH_TOKEN"
  file: "target/uberjar/rdf-validator-$TRAVIS_TAG-standalone.jar"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$

